### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by Fraser999**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/secure_serialisation/6)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib.rs, line 89 \[r1\]](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6#-K9qHu-AzTvxDAuIkpgo:-K9qHu-AzTvxDAuIkpgp:1111775146) ([raw file](https://github.com/maidsafe/secure_serialisation/blob/5a7436014a93858912d39669643ff4e5724f5d82/src/lib.rs#L89)):*
I suspect we should wrap all of these, that this library exposes key types of it's own perhaps? A convo for sure though. If we wrap these items then it may mean there is less chance of misuse ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6)*

**Comment by dirvine** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/lib.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6#-K9qISDwo7sahuYhNZg8:-K9qISDxxIfL44f_-7hr:-1491538891) ([raw file](https://github.com/maidsafe/secure_serialisation/blob/5a7436014a93858912d39669643ff4e5724f5d82/src/lib.rs#L100)):*
Interesting I had this previously but reverted. It does feel better to use Error here I admit. My concern was where we use Error elsewhere but it is fine as the compiler will alert us of any confusion so +1

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6)*

**Comment by dirvine** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/lib.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6#-K9qIpfbjIk5gBpOmvM5:-K9qIpfbjIk5gBpOmvM6:-819410075) ([raw file](https://github.com/maidsafe/secure_serialisation/blob/540a13261eb3fd8d9f927cffcc2f40178a63e40f/src/lib.rs#L125)):*
No sure here? We either wrap all these types or not, I agree the mix is wrong but not sure exporting other types is correct either. For now lets do this though and come back to it in a later update. Perhaps an issue to discuss would be good.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6)*

**Comment by Fraser999** [comment]
*[src/lib.rs, line 89 \[r1\]](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6#-K9qHu-AzTvxDAuIkpgo:-K9qIXl1GvRV3tiIaK4B:-1292712169) ([raw file](https://github.com/maidsafe/secure_serialisation/blob/5a7436014a93858912d39669643ff4e5724f5d82/src/lib.rs#L89)):*
Possibly, but we use the raw sodiumoxide types and functions extensively elsewhere.

If we were looking at doing that, it might make sense to do as we did for Crypto++ and try and provide an entire set of our own functions and types for use throughout all our libs.  Not sure it's worthwhile though - sodiumoxide seems to be significantly easier to use correctly than Crypto++ was.

I think if anything, I'd just not make these `pub use` at all and let users deal with the real sodiumoxide types.  I don't see that being a problem anwhere else we use those types.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6)*

**Comment by Fraser999** [comment]
*[src/lib.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6#-K9qIpfbjIk5gBpOmvM5:-K9qK2mcn6vcLcI1KxLD:-55951852) ([raw file](https://github.com/maidsafe/secure_serialisation/blob/540a13261eb3fd8d9f927cffcc2f40178a63e40f/src/lib.rs#L125)):*
I'm not sure about your point here?  I didn't change anything public  - only added `Nonce` to the imports as per the style guide...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/secure_serialisation/6)*

**Pull request merged**
